/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarRouteImport } from './routes/star'
import { Route as MagazineRouteImport } from './routes/magazine'
import { Route as InfluencerRouteImport } from './routes/influencer'
import { Route as EventRouteImport } from './routes/event'
import { Route as BrandAmbassadorRouteImport } from './routes/brand-ambassador'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesOfflineEventPrRouteImport } from './routes/services.offline-event-pr'
import { Route as ServicesInfluencerPrRouteImport } from './routes/services.influencer-pr'
import { Route as ServicesEditorialViralPrRouteImport } from './routes/services.editorial-viral-pr'
import { Route as ServicesCelebritySeedingRouteImport } from './routes/services.celebrity-seeding'
import { Route as ServicesBrandAmbassadorRouteImport } from './routes/services.brand-ambassador'
import { Route as ApiStarImageIdRouteImport } from './routes/api/star.image.$id'
import { Route as ApiMagazineImageIdRouteImport } from './routes/api/magazine.image.$id'
import { Route as ApiInfluencerImageIdRouteImport } from './routes/api/influencer.image.$id'
import { Route as ApiEventImageIdRouteImport } from './routes/api/event.image.$id'
import { Route as ApiBrandAmbassadorImageIdRouteImport } from './routes/api/brand-ambassador.image.$id'

const StarRoute = StarRouteImport.update({
  id: '/star',
  path: '/star',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineRoute = MagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerRoute = InfluencerRouteImport.update({
  id: '/influencer',
  path: '/influencer',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAmbassadorRoute = BrandAmbassadorRouteImport.update({
  id: '/brand-ambassador',
  path: '/brand-ambassador',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOfflineEventPrRoute = ServicesOfflineEventPrRouteImport.update({
  id: '/services/offline-event-pr',
  path: '/services/offline-event-pr',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInfluencerPrRoute = ServicesInfluencerPrRouteImport.update({
  id: '/services/influencer-pr',
  path: '/services/influencer-pr',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEditorialViralPrRoute =
  ServicesEditorialViralPrRouteImport.update({
    id: '/services/editorial-viral-pr',
    path: '/services/editorial-viral-pr',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCelebritySeedingRoute =
  ServicesCelebritySeedingRouteImport.update({
    id: '/services/celebrity-seeding',
    path: '/services/celebrity-seeding',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBrandAmbassadorRoute = ServicesBrandAmbassadorRouteImport.update({
  id: '/services/brand-ambassador',
  path: '/services/brand-ambassador',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStarImageIdRoute = ApiStarImageIdRouteImport.update({
  id: '/api/star/image/$id',
  path: '/api/star/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMagazineImageIdRoute = ApiMagazineImageIdRouteImport.update({
  id: '/api/magazine/image/$id',
  path: '/api/magazine/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInfluencerImageIdRoute = ApiInfluencerImageIdRouteImport.update({
  id: '/api/influencer/image/$id',
  path: '/api/influencer/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventImageIdRoute = ApiEventImageIdRouteImport.update({
  id: '/api/event/image/$id',
  path: '/api/event/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandAmbassadorImageIdRoute =
  ApiBrandAmbassadorImageIdRouteImport.update({
    id: '/api/brand-ambassador/image/$id',
    path: '/api/brand-ambassador/image/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-ambassador': typeof BrandAmbassadorRoute
  '/event': typeof EventRoute
  '/influencer': typeof InfluencerRoute
  '/magazine': typeof MagazineRoute
  '/star': typeof StarRoute
  '/services/brand-ambassador': typeof ServicesBrandAmbassadorRoute
  '/services/celebrity-seeding': typeof ServicesCelebritySeedingRoute
  '/services/editorial-viral-pr': typeof ServicesEditorialViralPrRoute
  '/services/influencer-pr': typeof ServicesInfluencerPrRoute
  '/services/offline-event-pr': typeof ServicesOfflineEventPrRoute
  '/api/brand-ambassador/image/$id': typeof ApiBrandAmbassadorImageIdRoute
  '/api/event/image/$id': typeof ApiEventImageIdRoute
  '/api/influencer/image/$id': typeof ApiInfluencerImageIdRoute
  '/api/magazine/image/$id': typeof ApiMagazineImageIdRoute
  '/api/star/image/$id': typeof ApiStarImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-ambassador': typeof BrandAmbassadorRoute
  '/event': typeof EventRoute
  '/influencer': typeof InfluencerRoute
  '/magazine': typeof MagazineRoute
  '/star': typeof StarRoute
  '/services/brand-ambassador': typeof ServicesBrandAmbassadorRoute
  '/services/celebrity-seeding': typeof ServicesCelebritySeedingRoute
  '/services/editorial-viral-pr': typeof ServicesEditorialViralPrRoute
  '/services/influencer-pr': typeof ServicesInfluencerPrRoute
  '/services/offline-event-pr': typeof ServicesOfflineEventPrRoute
  '/api/brand-ambassador/image/$id': typeof ApiBrandAmbassadorImageIdRoute
  '/api/event/image/$id': typeof ApiEventImageIdRoute
  '/api/influencer/image/$id': typeof ApiInfluencerImageIdRoute
  '/api/magazine/image/$id': typeof ApiMagazineImageIdRoute
  '/api/star/image/$id': typeof ApiStarImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-ambassador': typeof BrandAmbassadorRoute
  '/event': typeof EventRoute
  '/influencer': typeof InfluencerRoute
  '/magazine': typeof MagazineRoute
  '/star': typeof StarRoute
  '/services/brand-ambassador': typeof ServicesBrandAmbassadorRoute
  '/services/celebrity-seeding': typeof ServicesCelebritySeedingRoute
  '/services/editorial-viral-pr': typeof ServicesEditorialViralPrRoute
  '/services/influencer-pr': typeof ServicesInfluencerPrRoute
  '/services/offline-event-pr': typeof ServicesOfflineEventPrRoute
  '/api/brand-ambassador/image/$id': typeof ApiBrandAmbassadorImageIdRoute
  '/api/event/image/$id': typeof ApiEventImageIdRoute
  '/api/influencer/image/$id': typeof ApiInfluencerImageIdRoute
  '/api/magazine/image/$id': typeof ApiMagazineImageIdRoute
  '/api/star/image/$id': typeof ApiStarImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-ambassador'
    | '/event'
    | '/influencer'
    | '/magazine'
    | '/star'
    | '/services/brand-ambassador'
    | '/services/celebrity-seeding'
    | '/services/editorial-viral-pr'
    | '/services/influencer-pr'
    | '/services/offline-event-pr'
    | '/api/brand-ambassador/image/$id'
    | '/api/event/image/$id'
    | '/api/influencer/image/$id'
    | '/api/magazine/image/$id'
    | '/api/star/image/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-ambassador'
    | '/event'
    | '/influencer'
    | '/magazine'
    | '/star'
    | '/services/brand-ambassador'
    | '/services/celebrity-seeding'
    | '/services/editorial-viral-pr'
    | '/services/influencer-pr'
    | '/services/offline-event-pr'
    | '/api/brand-ambassador/image/$id'
    | '/api/event/image/$id'
    | '/api/influencer/image/$id'
    | '/api/magazine/image/$id'
    | '/api/star/image/$id'
  id:
    | '__root__'
    | '/'
    | '/brand-ambassador'
    | '/event'
    | '/influencer'
    | '/magazine'
    | '/star'
    | '/services/brand-ambassador'
    | '/services/celebrity-seeding'
    | '/services/editorial-viral-pr'
    | '/services/influencer-pr'
    | '/services/offline-event-pr'
    | '/api/brand-ambassador/image/$id'
    | '/api/event/image/$id'
    | '/api/influencer/image/$id'
    | '/api/magazine/image/$id'
    | '/api/star/image/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandAmbassadorRoute: typeof BrandAmbassadorRoute
  EventRoute: typeof EventRoute
  InfluencerRoute: typeof InfluencerRoute
  MagazineRoute: typeof MagazineRoute
  StarRoute: typeof StarRoute
  ServicesBrandAmbassadorRoute: typeof ServicesBrandAmbassadorRoute
  ServicesCelebritySeedingRoute: typeof ServicesCelebritySeedingRoute
  ServicesEditorialViralPrRoute: typeof ServicesEditorialViralPrRoute
  ServicesInfluencerPrRoute: typeof ServicesInfluencerPrRoute
  ServicesOfflineEventPrRoute: typeof ServicesOfflineEventPrRoute
  ApiBrandAmbassadorImageIdRoute: typeof ApiBrandAmbassadorImageIdRoute
  ApiEventImageIdRoute: typeof ApiEventImageIdRoute
  ApiInfluencerImageIdRoute: typeof ApiInfluencerImageIdRoute
  ApiMagazineImageIdRoute: typeof ApiMagazineImageIdRoute
  ApiStarImageIdRoute: typeof ApiStarImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/star': {
      id: '/star'
      path: '/star'
      fullPath: '/star'
      preLoaderRoute: typeof StarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine': {
      id: '/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof MagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer': {
      id: '/influencer'
      path: '/influencer'
      fullPath: '/influencer'
      preLoaderRoute: typeof InfluencerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-ambassador': {
      id: '/brand-ambassador'
      path: '/brand-ambassador'
      fullPath: '/brand-ambassador'
      preLoaderRoute: typeof BrandAmbassadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/offline-event-pr': {
      id: '/services/offline-event-pr'
      path: '/services/offline-event-pr'
      fullPath: '/services/offline-event-pr'
      preLoaderRoute: typeof ServicesOfflineEventPrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/influencer-pr': {
      id: '/services/influencer-pr'
      path: '/services/influencer-pr'
      fullPath: '/services/influencer-pr'
      preLoaderRoute: typeof ServicesInfluencerPrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/editorial-viral-pr': {
      id: '/services/editorial-viral-pr'
      path: '/services/editorial-viral-pr'
      fullPath: '/services/editorial-viral-pr'
      preLoaderRoute: typeof ServicesEditorialViralPrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/celebrity-seeding': {
      id: '/services/celebrity-seeding'
      path: '/services/celebrity-seeding'
      fullPath: '/services/celebrity-seeding'
      preLoaderRoute: typeof ServicesCelebritySeedingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/brand-ambassador': {
      id: '/services/brand-ambassador'
      path: '/services/brand-ambassador'
      fullPath: '/services/brand-ambassador'
      preLoaderRoute: typeof ServicesBrandAmbassadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/star/image/$id': {
      id: '/api/star/image/$id'
      path: '/api/star/image/$id'
      fullPath: '/api/star/image/$id'
      preLoaderRoute: typeof ApiStarImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/magazine/image/$id': {
      id: '/api/magazine/image/$id'
      path: '/api/magazine/image/$id'
      fullPath: '/api/magazine/image/$id'
      preLoaderRoute: typeof ApiMagazineImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/influencer/image/$id': {
      id: '/api/influencer/image/$id'
      path: '/api/influencer/image/$id'
      fullPath: '/api/influencer/image/$id'
      preLoaderRoute: typeof ApiInfluencerImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event/image/$id': {
      id: '/api/event/image/$id'
      path: '/api/event/image/$id'
      fullPath: '/api/event/image/$id'
      preLoaderRoute: typeof ApiEventImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-ambassador/image/$id': {
      id: '/api/brand-ambassador/image/$id'
      path: '/api/brand-ambassador/image/$id'
      fullPath: '/api/brand-ambassador/image/$id'
      preLoaderRoute: typeof ApiBrandAmbassadorImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandAmbassadorRoute: BrandAmbassadorRoute,
  EventRoute: EventRoute,
  InfluencerRoute: InfluencerRoute,
  MagazineRoute: MagazineRoute,
  StarRoute: StarRoute,
  ServicesBrandAmbassadorRoute: ServicesBrandAmbassadorRoute,
  ServicesCelebritySeedingRoute: ServicesCelebritySeedingRoute,
  ServicesEditorialViralPrRoute: ServicesEditorialViralPrRoute,
  ServicesInfluencerPrRoute: ServicesInfluencerPrRoute,
  ServicesOfflineEventPrRoute: ServicesOfflineEventPrRoute,
  ApiBrandAmbassadorImageIdRoute: ApiBrandAmbassadorImageIdRoute,
  ApiEventImageIdRoute: ApiEventImageIdRoute,
  ApiInfluencerImageIdRoute: ApiInfluencerImageIdRoute,
  ApiMagazineImageIdRoute: ApiMagazineImageIdRoute,
  ApiStarImageIdRoute: ApiStarImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
