/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarRouteImport } from './routes/star'
import { Route as MagazineRouteImport } from './routes/magazine'
import { Route as InfluencerRouteImport } from './routes/influencer'
import { Route as EventRouteImport } from './routes/event'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStarImageIdRouteImport } from './routes/api/star.image.$id'
import { Route as ApiMagazineImageIdRouteImport } from './routes/api/magazine.image.$id'
import { Route as ApiInfluencerImageIdRouteImport } from './routes/api/influencer.image.$id'
import { Route as ApiEventImageIdRouteImport } from './routes/api/event.image.$id'

const StarRoute = StarRouteImport.update({
  id: '/star',
  path: '/star',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineRoute = MagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerRoute = InfluencerRouteImport.update({
  id: '/influencer',
  path: '/influencer',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStarImageIdRoute = ApiStarImageIdRouteImport.update({
  id: '/api/star/image/$id',
  path: '/api/star/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMagazineImageIdRoute = ApiMagazineImageIdRouteImport.update({
  id: '/api/magazine/image/$id',
  path: '/api/magazine/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInfluencerImageIdRoute = ApiInfluencerImageIdRouteImport.update({
  id: '/api/influencer/image/$id',
  path: '/api/influencer/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventImageIdRoute = ApiEventImageIdRouteImport.update({
  id: '/api/event/image/$id',
  path: '/api/event/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/event': typeof EventRoute
  '/influencer': typeof InfluencerRoute
  '/magazine': typeof MagazineRoute
  '/star': typeof StarRoute
  '/api/event/image/$id': typeof ApiEventImageIdRoute
  '/api/influencer/image/$id': typeof ApiInfluencerImageIdRoute
  '/api/magazine/image/$id': typeof ApiMagazineImageIdRoute
  '/api/star/image/$id': typeof ApiStarImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/event': typeof EventRoute
  '/influencer': typeof InfluencerRoute
  '/magazine': typeof MagazineRoute
  '/star': typeof StarRoute
  '/api/event/image/$id': typeof ApiEventImageIdRoute
  '/api/influencer/image/$id': typeof ApiInfluencerImageIdRoute
  '/api/magazine/image/$id': typeof ApiMagazineImageIdRoute
  '/api/star/image/$id': typeof ApiStarImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/event': typeof EventRoute
  '/influencer': typeof InfluencerRoute
  '/magazine': typeof MagazineRoute
  '/star': typeof StarRoute
  '/api/event/image/$id': typeof ApiEventImageIdRoute
  '/api/influencer/image/$id': typeof ApiInfluencerImageIdRoute
  '/api/magazine/image/$id': typeof ApiMagazineImageIdRoute
  '/api/star/image/$id': typeof ApiStarImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/event'
    | '/influencer'
    | '/magazine'
    | '/star'
    | '/api/event/image/$id'
    | '/api/influencer/image/$id'
    | '/api/magazine/image/$id'
    | '/api/star/image/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/event'
    | '/influencer'
    | '/magazine'
    | '/star'
    | '/api/event/image/$id'
    | '/api/influencer/image/$id'
    | '/api/magazine/image/$id'
    | '/api/star/image/$id'
  id:
    | '__root__'
    | '/'
    | '/event'
    | '/influencer'
    | '/magazine'
    | '/star'
    | '/api/event/image/$id'
    | '/api/influencer/image/$id'
    | '/api/magazine/image/$id'
    | '/api/star/image/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventRoute: typeof EventRoute
  InfluencerRoute: typeof InfluencerRoute
  MagazineRoute: typeof MagazineRoute
  StarRoute: typeof StarRoute
  ApiEventImageIdRoute: typeof ApiEventImageIdRoute
  ApiInfluencerImageIdRoute: typeof ApiInfluencerImageIdRoute
  ApiMagazineImageIdRoute: typeof ApiMagazineImageIdRoute
  ApiStarImageIdRoute: typeof ApiStarImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/star': {
      id: '/star'
      path: '/star'
      fullPath: '/star'
      preLoaderRoute: typeof StarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine': {
      id: '/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof MagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer': {
      id: '/influencer'
      path: '/influencer'
      fullPath: '/influencer'
      preLoaderRoute: typeof InfluencerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/star/image/$id': {
      id: '/api/star/image/$id'
      path: '/api/star/image/$id'
      fullPath: '/api/star/image/$id'
      preLoaderRoute: typeof ApiStarImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/magazine/image/$id': {
      id: '/api/magazine/image/$id'
      path: '/api/magazine/image/$id'
      fullPath: '/api/magazine/image/$id'
      preLoaderRoute: typeof ApiMagazineImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/influencer/image/$id': {
      id: '/api/influencer/image/$id'
      path: '/api/influencer/image/$id'
      fullPath: '/api/influencer/image/$id'
      preLoaderRoute: typeof ApiInfluencerImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event/image/$id': {
      id: '/api/event/image/$id'
      path: '/api/event/image/$id'
      fullPath: '/api/event/image/$id'
      preLoaderRoute: typeof ApiEventImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventRoute: EventRoute,
  InfluencerRoute: InfluencerRoute,
  MagazineRoute: MagazineRoute,
  StarRoute: StarRoute,
  ApiEventImageIdRoute: ApiEventImageIdRoute,
  ApiInfluencerImageIdRoute: ApiInfluencerImageIdRoute,
  ApiMagazineImageIdRoute: ApiMagazineImageIdRoute,
  ApiStarImageIdRoute: ApiStarImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
